automation/urls.py
from django.conf import settings

from django.urls import path
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from . import views

app_name = "automation" 

urlpatterns = [
    #################################### Manage Account ####################################
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeFormView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetFormView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    #################################### Main Views ####################################
    path('', views.HomeView.as_view(), name='home'),
    path('user/apps/', views.UserAppsListView.as_view(), name='user_apps'),
    path('user/apps/create/', views.CreateAppView.as_view(), name='create_app'),
    path('user/apps/<slug:slug>/', views.DetailAppView.as_view(), name='app_detail'),
    path('user/apps/<slug:slug>/update/', views.UpdateAppView.as_view(), name='app_update'),
    path('user/apps/<slug:slug>/delete/', views.DeleteAppView.as_view(), name='app_delete'),

    #################################### Test View ####################################
    path('user/apps/<slug:slug>/test/', views.TestAppsRedirectView.as_view(), name='app_test'),

    #################################### Accessibility ####################################
    path('switch-language/', views.switch_language, name='switch_language'),

]
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

automation/templates/automation/hierarchy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XML to HTML</title>
    <style>
        .ui_container {
            max-width: 800px;
            margin: auto;
        }
        .ui_element {
            border: 1px solid #ccc;
            padding: 2px 2px;
            transition: all 0.3s ease;
        }
    </style>

</head>
<body>
    <div class="ui_container">
        <!-- Render the HTML content as safe HTML -->
        {{ html_content|safe }}
    </div>
</body>
</html>

automation/templates/automation/home.html
{% extends "automation/layout.html" %}
{% load i18n %}
{% block title %}{% trans "Home" %}{% endblock %}

{% block body %}
<div class="form-container">
    <h1>{% trans "Welcome to App Manager" %}</h1>
    <h2>{% trans "Welcome to App Manager" %}</h2>
    
    <h3>{% trans "Welcome to App Manager" %}</h3>
    <a href="{% url 'automation:user_apps' %}">{% trans "Start App Manager" %}</a>
</div>

{% endblock %}

automation/templates/automation/layout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% trans "Automation Testing" %}{% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v6.6.0/css/all.css">
    <link rel="stylesheet" href="{% static 'automation/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>

<body>
    {% if messages %}
    {% for message in messages %}
        <div class=" mb-0 alert alert-{% if message.tags == 'error'%}danger{% else %}{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'automation:home' %}">{% trans "App Manager" %}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'automation:home' %}">{% trans "Home" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'automation:user_apps' %}">{% trans "Apps" %}</a>
                    </li>
                    <li class="nav-item">
                        <button id="toggle-contrast" class="nav_options btn"><i id="dark_icon" class="fa-solid fa-sun" style="color: #FFD43B;"></i></button>
                    </li>

                    <li class="nav-item ms-auto">
                        <ul class="navbar-nav flex-row">
                            <li class="nav-item">
                                <select id="language-switcher" class="btn-outline-secondary nav_options form-control" onchange="switchLanguage()">
                                    <option value="en" {% if request.LANGUAGE_CODE == 'en' %}selected{% endif %}>{% trans "English" %}</option>
                                    <option value="fr" {% if request.LANGUAGE_CODE == 'fr' %}selected{% endif %}>{% trans "French" %}</option>
                                </select>
                            </li>
                            <li class="nav-item">
                                <select id="font-size-switcher" class="btn-outline-secondary nav_options form-control" onchange="changeFontSize()">
                                    <option value="small">{% trans "Small" %}</option>
                                    <option value="medium" selected>{% trans "Medium" %}</option>
                                    <option value="large">{% trans "Large" %}</option>
                                    <option value="vlarge">{% trans "Very Large" %}</option>
                                </select>
                            </li>
                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'automation:password_change' %}">{% trans "Change password" %}</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <form method="post" action="{% url 'automation:logout' %}" id="logout-form">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-link">{% trans "Logout" %}</button>
                                </form>
                                {% else %}
                                <a class="nav_options btn btn-outline-secondary" href="{% url 'automation:login' %}">{% trans "Login" %}</a>
                                {% endif %}
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class=" body_container">
        {% block body %}
        {% endblock %}
    </div>

    <footer class="footer mt-2">
        <div class="container">
            <p>&copy; {% trans "2024 Your Company. All rights reserved." %}</p>
            <p><a href="#">{% trans "Privacy Policy" %}</a> | <a href="#">{% trans "Terms of Service" %}</a></p>
        </div>
    </footer>

    <script src="{% static 'automation/index.js' %}"></script>
    <script>
        function switchLanguage() {
            const language = document.getElementById('language-switcher').value;
            window.location.href = "{% url 'automation:switch_language' %}?language=" + language;
        }
    </script>
  {% block scripts %}
  {% endblock %}
</body>
</html>