app/automation/urls.py
from django.conf import settings

from django.urls import path
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from . import views

app_name = "automation" 
urlpatterns = [
    #################################### Manage Account ####################################
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeFormView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetFormView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    #################################### Main Views ####################################
    path('', views.HomeView.as_view(), name='home'),
    path('user/apps/', views.UserAppsListView.as_view(), name='user_apps'),
    path('user/apps/create/', views.CreateAppView.as_view(), name='create_app'),
    path('user/apps/<slug:slug>/', views.DetailAppView.as_view(), name='app_detail'),
    path('user/apps/<slug:slug>/update/', views.UpdateAppView.as_view(), name='app_update'),
    path('user/apps/<slug:slug>/delete/', views.DeleteAppView.as_view(), name='app_delete'),

    #################################### Test View ####################################
    path('user/apps/<slug:slug>/test/', views.TestAppsRedirectView.as_view(), name='app_test'),

    #################################### Accessibility ####################################
    path('switch-language/', views.switch_language, name='switch_language'),

]
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("automation.urls", namespace="automation")),
]

app/automation/models.py
import os
import random
import string
import shutil
from django.db import models
from django.contrib.auth import get_user_model

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()

def get_upload_path(instance, filename):
    return os.path.join(instance.slug, filename)

def generate_unique_slug(length=8):
    chars = string.ascii_letters + string.digits
    return ''.join(random.choice(chars) for _ in range(length))

class AVD(models.Model):
    name = models.CharField(max_length=150)
    sdk_root = models.CharField(max_length=255)
    service_url = models.URLField(max_length=200)
    booted = models.BooleanField(default=False)

    def clean(self):
        if not os.path.isdir(self.sdk_root):
            raise ValidationError(_("The folder path does not exist.")) 

    def __str__(self):
        return self.name

class APP(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, verbose_name=_("App name"))
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    screen_changed = models.BooleanField(default=False)
    is_tested = models.BooleanField(default=False)

    apk_file_path = models.FileField(upload_to=get_upload_path, verbose_name=_("APK File Path"))
    ui_hierarchy = models.FileField(upload_to=get_upload_path, blank=True, null=True)
    video_recording_path = models.FileField(upload_to=get_upload_path, blank=True, null=True)
    first_screen_screenshot_path = models.ImageField(upload_to=get_upload_path, blank=True, null=True)
    second_screen_screenshot_path = models.ImageField(upload_to=get_upload_path, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            unique_slug = generate_unique_slug()
            while APP.objects.filter(slug=unique_slug).exists():
                unique_slug = generate_unique_slug()
            self.slug = unique_slug

        for field in ['apk_file_path', 'ui_hierarchy',
                      'video_recording_path', 'first_screen_screenshot_path', 
                      'second_screen_screenshot_path']:
            try:      
                current_file = getattr(self, field)
                if current_file:
                    old_file = APP.objects.get(pk=self.pk)
                    old_file_path = getattr(old_file, field).path
                    if old_file_path != current_file.path:
                        if os.path.isfile(old_file_path):
                            os.remove(old_file_path)
            except:
                pass
                            
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        folder_path = os.path.dirname(self.apk_file_path.path)
        if os.path.isdir(folder_path):
            shutil.rmtree(folder_path)

        super().delete(*args, **kwargs)
         
    def __str__(self):
        return self.name

app/automation/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import APP
from django.utils.translation import gettext_lazy as _

ERROR_MESSAGES = {
    'required': _("This field is required."),
    'invalid': _("Enter a valid value."),
    'max_length': _("Ensure this value has at most {max_length} characters (it has {length})."),
    'min_length': _("Ensure this value has at least {min_length} characters (it has {length})."),
    'password_mismatch': _("The two password fields didn't match."),
}

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        error_messages={
            'required': ERROR_MESSAGES['required'],
            'invalid': ERROR_MESSAGES['invalid'],
        }
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        error_messages = {
            'username': {
                'required': ERROR_MESSAGES['required'],
                'max_length': ERROR_MESSAGES['max_length'],
            },
            'email': {
                'required': ERROR_MESSAGES['required'],
                'invalid': ERROR_MESSAGES['invalid'],
            },
            'password1': {
                'required': ERROR_MESSAGES['required'],
                'min_length': ERROR_MESSAGES['min_length'],
            },
            'password2': {
                'required': ERROR_MESSAGES['required'],
                'min_length': ERROR_MESSAGES['min_length'],
                'password_mismatch': ERROR_MESSAGES['password_mismatch'],  # Custom message for password mismatch
            },
        }       

class APPForm(forms.ModelForm):
    
    class Meta:
        model = APP
        fields = ['name', 'apk_file_path']
        labels = {
            'name': _("App name"),
            'apk_file_path': _("APK File Path"),
        }
        help_texts = {
            'name': _("Enter the name of the application."),
            'apk_file_path': _("Choose an APK."),
        }
        error_messages = {
            'name': {
                'required': ERROR_MESSAGES['required'],
                'max_length': ERROR_MESSAGES['max_length'],
            },
            'apk_file_path': {
                'required': ERROR_MESSAGES['required'],
            },
        }

    def clean_apk_file_path(self):
        apk_file = self.cleaned_data.get('apk_file_path')

        if apk_file:
            if not apk_file.name.endswith('.apk'):
                raise forms.ValidationError(_("The file must be an APK."))

        return apk_file

app/automation/views.py
from django.conf import settings

from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy

from django.utils import translation
from django.utils.translation import gettext as _

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView, ListView, RedirectView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from .testing import AppiumTestAutomation
from .models import APP, AVD
from .forms import RegisterForm, APPForm
from .xml_to_html import XMLToHTMLConverter


    
#################################### Manage Account ####################################

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('automation:login')

class PasswordChangeFormView(auth_views.PasswordChangeView):
    def get_success_url(self) :
        messages.success(self.request, _("Password's been changed successfully!"))
        return reverse_lazy('automation:login')

class PasswordResetFormView(auth_views.PasswordResetView):
    def get_success_url(self) :
        messages.success(self.request, _("We've emailed you instructions for setting your password. You should receive the email shortly!"))
        return reverse_lazy('automation:password_reset')

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    def get_success_url(self):
        messages.success(self.request, _("Password's been changed successfully, try to login"))
        return reverse_lazy('automation:login') 

#################################### Main Views ####################################

class HomeView(TemplateView):
    template_name = 'automation/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 

        context['greeting'] = _("Welcome to App Manager")
        return context

class UserAppsListView(LoginRequiredMixin, ListView):
    template_name = 'automation/apps_list.html'
    paginate_by = 14

    def get_queryset(self):
        apps = APP.objects.filter(uploaded_by=self.request.user).order_by('created_at')
        return apps
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CreateAppView(LoginRequiredMixin, CreateView):
    model = APP
    form_class = APPForm
    template_name = 'automation/app_form.html'

    def form_valid(self, form):
        form.instance.uploaded_by = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        messages.success(self.request, _("The App saved successfully"))
        return reverse_lazy('automation:app_detail', kwargs={'slug': self.object.slug})

class DetailAppView(LoginRequiredMixin, DetailView):
    model = APP
    template_name = 'automation/app_detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.uploaded_by != self.request.user:
            raise Http404(_("App not found."))
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        app = self.get_object()
        if app.is_tested:
            converter = XMLToHTMLConverter(app.ui_hierarchy.path)
            html_content = converter.convert()
            context['hierarchy_content'] = html_content
        return context

class UpdateAppView(LoginRequiredMixin, UpdateView):
    model = APP
    form_class = APPForm
    template_name = 'automation/app_form.html'
    
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.uploaded_by != self.request.user:
            raise Http404(_("App not found."))
        return obj
    
    def get_success_url(self):
        messages.success(self.request, _("The App saved successfully"))
        return reverse_lazy('automation:app_detail', kwargs={'slug': self.object.slug})

class DeleteAppView(LoginRequiredMixin, DeleteView):
    model = APP
    template_name = 'automation/app_delete.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.uploaded_by != self.request.user:
            raise Http404(_("App not found."))
        return obj
    
    def get_success_url(self):
        messages.success(self.request, _("The App saved successfully"))
        return reverse_lazy('automation:user_apps')

#################################### Test View ####################################

class TestAppsRedirectView(RedirectView):
    model = APP
    pattern_name = 'automation:app_detail'

    def get_redirect_url(self, *args, **kwargs):
        app = get_object_or_404(APP, slug=kwargs['slug'])

        # Retrieve the last AVD instance from the database
        avd = AVD.objects.order_by('-id').first()
        device = AppiumTestAutomation(avd)

        result = device.run_test(app) 
        if result['status'] == 'success':
            app.screen_changed = result['action_taken']
            app.is_tested = True
            app.save()
            messages.success(self.request,_("The app's been Tested successfully"))
        else:
            messages.error(self.request,_("Unfortunately an error happened, please try again.."))
            print(result['cause'])
        return super().get_redirect_url(*args, **kwargs)

#################################### Accessibility ####################################

def switch_language(request):
    language = request.GET.get('language', 'en')
    translation.activate(language)
    response = redirect(request.META.get('HTTP_REFERER'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    return response

app/automation/templates/automation/app_delete.html
{% extends "automation/layout.html" %}
{% load i18n %}
{% block title %}{% trans "Application" %}{% endblock %}

{% block body %}

    <div class="mb-4 page_title_holder">
        <h2 class="page_title">{% trans "Confirm Delete" %}</h2>
    </div> 

    <form method="post">
        {% csrf_token %}
        <div class="card border-danger mb-3 " style="">
            <div class="card-header">{% trans "Delete" %}</div>
            <div class="card-body text-danger">
                <h5 class="card-title">{% trans "Are you sure you want to delete application" %} "{{ object.name }}"?</h5>
                <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>
            </div>
        </div>
    </form>
    <a href="{% url 'automation:app_detail' slug=object.slug %}">{% trans "Cancel" %}</a>
        
{% endblock %}

app/automation/templates/automation/app_detail.html
{% extends "automation/layout.html" %}
{% load i18n %}
{% block title %}{% trans "Application" %}{% endblock %}
{% block body %}
<div class="container mt-4">
    <div class="mb-4 page_title_holder">
        <h2 class="page_title">{{ object.name }}</h2>
    </div>

    <h3># {{ object.id }} {% trans "Uploaded by" %} "{{ object.uploaded_by.username }}"</h3>

    <div class="row mt-4">
        <div>
            <h3>{% trans "Details:" %}</h3>
            <p><strong>{% trans "APK File" %}:</strong> <a href="{{ object.apk_file_path.url }}"  download>{% trans "Click to download" %} <i class="fa-solid fa-download fa-l" style="color: #FFD43B;"></i></a></p>
            <p><strong>{% trans "Created At" %}:</strong> {{ object.created_at|date:"F j, Y, g:i a" }}</p>
            <p><strong>{% trans "Updated At" %}:</strong> {{ object.updated_at|date:"F j, Y, g:i a" }}</p>
            <p>
                <strong>{% trans "Tested" %}:</strong>
                {% if object.is_tested %}
                <i class="fa-solid fa-check fa-xl" style="color: #74C0FC;"></i>                        
                {% else %}
                <i class="fa-solid fa-xmark" style="color: #ff0033;"></i>
                {% endif %}
            </p>
            <p>
                <strong>{% trans "Screen Changed" %}:</strong>
                {% if object.screen_changed %}
                <i class="fa-solid fa-check fa-xl" style="color: #74C0FC;"></i>                        
                {% else %}
                <i class="fa-solid fa-xmark" style="color: #ff0033;"></i>
                {% endif %}
            </p>
        </div>

    </div>

    <div class="mt-4">
        <a href="{% url 'automation:user_apps' %}" class="btn btn-outline-secondary">{% trans "Back to My Apps" %}</a>
        <a href="{% url 'automation:app_delete' object.slug %}" class="btn btn-outline-danger">{% trans "Delete" %}</a>
        <a href="{% url 'automation:app_update' object.slug %}" class="btn btn-outline-info">{% trans "Edit" %}</a>
        <a id="test_btn" href="{% url 'automation:app_test' object.slug %}" class="ms-4 btn btn-outline-success">{% trans "Run Test" %}</a>
        <button id="loading_btn" class="ms-4 btn btn-outline-success" style="display: none" disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span role="status">{% trans "Test is Loading" %}...</span>
        </button>

    </div>

    {% comment %}         Test Section             {% endcomment %}
    {% if object.ui_hierarchy %}
    
    <hr>
    <div class="mb-4 page_title_holder">
        <h2 class="page_title">{% trans "Test Result" %}</h2>
    </div>
    <h2>{% trans "Media:" %}</h2>
    <div class="row mt-4 justify-content-center">
        <div class="col-md-4">
            <p>{% trans "Video Recording" %}</p>
            <video controls  style="height: 500px; width:280px;">
                <source src="{{ object.video_recording_path.url }}" type="video/mp4">
                {% trans "Your browser does not support the video tag." %}
            </video>
        </div>
        <div class="col-md-4">
            <p>{% trans "First Screen Screenshot" %}</p>
            <img src="{{ object.first_screen_screenshot_path.url }}"  alt="{% trans 'First Screen Screenshot' %}" style="height: 500px; width:280px;">
        </div>
        <div class="col-md-4">
            <p >{% trans "Second Screen Screenshot" %}</p>
            <img src="{{ object.second_screen_screenshot_path.url }}"  alt="{% trans 'Second Screen Screenshot' %}" style="height: 500px; width:280px;">
        </div>
    </div>
    {% endif %}

    {% comment %}         UI Section             {% endcomment %}

    {% if hierarchy_content %}
    <h2 class="mt-4">{% trans "UI Elements:" %}</h2>
    <a href="{{ object.ui_hierarchy.url }}"  download>{% trans "Click to download .xml" %} <i class="fa-solid fa-download fa-l" style="color: #FFD43B;"></i></a>
    <div class="mt-4 ui_container ">
        {{ hierarchy_content|safe }}
    </div>
    {% endif %}
    
</div>

{% endblock %}

{% block scripts %}
<script>
    test_btn = document.getElementById('test_btn')
    test_btn.addEventListener('click', function() {
        test_btn.style.display = 'none';
        document.getElementById('loading_btn').style.display = 'inline-block';
    });
</script>

{% endblock %}

app/automation/templates/automation/app_form.html
{% extends "automation/layout.html" %}
{% load i18n %}
{% block title %}{% trans "Application" %}{% endblock %}

{% block body %}

    <div class="mb-4 page_title_holder">
        <h2 class="page_title">
            {% if object %}
                {% trans "Edit " %}{{object.name}}
            {% else %}
                {% trans "Create Application" %}
            {% endif %}
        </h2>

    </div> 

    <form method="post" enctype="multipart/form-data" class="styled-form">

        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-container">
            <button type="submit">{% trans "Save" %}</button>
        </div>
        
    </form>
    

{% endblock %}

app/automation/templates/automation/apps_list.html
{% extends "automation/layout.html" %}
{% load i18n %}

{% block title %}{% trans "Application Management" %}{% endblock %}
{% block body %}

    <div class="mb-4 page_title_holder">
        <h2 class="page_title">{% trans "Manage Your Apps" %}</h2>
    </div> 

    <div class="container mt-5">
        <a class=" mb-1 btn btn-outline-info" href="{% url 'automation:create_app' %}" role="button">{% trans "Create new App" %}</a>

        <table class="table table-dark table-hover text-center">
            <thead >
                <tr>
                    <th scope="col">#</th>
                    <th>{% trans "App Name" %}</th>
                    <th>{% trans "Uploaded At" %}</th>
                    <th>{% trans "Tested" %}</th>
                    <th>{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody >
                {% for app in object_list %}
                <tr>
                    <th scope="row">{{ app.id }}</th>
                    <td>{{app.name}}</td>
                    <td>{{app.created_at}}</td>
                    
                    <td>
                        {% if app.is_tested %}
                        <i class="fa-solid fa-check fa-xl" style="color: #74C0FC;"></i>                        
                        {% else %}
                        <i class="fa-solid fa-xmark fa-xl" style="color: #ff0033;"></i>
                        {% endif %}
                    </td>

                    <td>
                        <a href="{% url 'automation:app_detail' slug=app.slug %}"><i class="fa-solid fa-eye fa-xl" style="color: #74C0FC; padding-right:10px;"></i></a>
                        <a href="{% url 'automation:app_update' slug=app.slug %}"><i class="fa-solid fa-pen-to-square fa-xl" style="color: #74C0FC; padding-right:10px;"></i></a>
                        <a href="{% url 'automation:app_delete' slug=app.slug %}"><i class="fa-solid fa-trash fa-xl" style="color: #b20606;"></i></a>
                    </td>
                </tr>
                {% empty %}
                </tr>

                    <td colspan="5">{% trans "No apps found." %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>        
        
        <!-- Pagination controls -->
        <div class="pagination">
            <div class="step-links">
                <div class="previous">
                    {% if page_obj.has_previous %}
                    <a href="?{{ query_params }}&page={{ page_obj.previous_page_number }}">&laquo; {% trans "Previous" %}</a>
                    {% else %}
                    <span class="disabled">&laquo; {% trans "Previous" %}</span>
                    {% endif %}
                </div>
                <div class="next">
                    {% if page_obj.has_next %}
                    <a href="?{{ query_params }}&page={{ page_obj.next_page_number }}">{% trans "Next" %} &raquo;</a>
                    {% else %}
                    <span class="disabled">{% trans "Next" %} &raquo;</span>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
        

{% endblock %}

app/automation/templates/automation/hierarchy.html
<!-- your_template.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XML to HTML</title>
    <style>
        .ui_container {
            max-width: 800px;
            margin: auto;
        }
        .ui_element {
            border: 1px solid #ccc;
            padding: 2px 2px;
            transition: all 0.3s ease;
        }
    </style>

</head>
<body>
    <div class="ui_container">
        <!-- Render the HTML content as safe HTML -->
        {{ html_content|safe }}
    </div>
</body>
</html>

app/automation/templates/automation/home.html
{% extends "automation/layout.html" %}
{% load i18n %}
{% block title %}{% trans "Home" %}{% endblock %}

{% block body %}
<div class="form-container">
    <h1>{% trans "Welcome to App Manager" %}</h1>
    <h2>{% trans "Welcome to App Manager" %}</h2>
    
    <h3>{% trans "Welcome to App Manager" %}</h3>
    <a href="#">{% trans "Start App Manager" %}</a>
</div>

{% endblock %}

app/automation/templates/automation/layout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% trans "Automation Testing" %}{% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v6.6.0/css/all.css">
    <link rel="stylesheet" href="{% static 'automation/sstyle.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>

<body>
    {% if messages %}
    {% for message in messages %}
        <div class=" mb-0 alert alert-{% if message.tags == 'error'%}danger{% else %}{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">{% trans "App Manager" %}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'automation:home' %}">{% trans "Home" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'automation:user_apps' %}">{% trans "Apps" %}</a>
                    </li>
                    <li class="nav-item">
                        <button id="toggle-contrast" class="nav_options btn"><i id="dark_icon" class="fa-solid fa-sun" style="color: #FFD43B;"></i></button>
                    </li>
                    <!-- Add this wrapper class to align all the remaining items to the left -->
                    <li class="nav-item ms-auto">
                        <ul class="navbar-nav flex-row">
                            <li class="nav-item">
                                <select id="language-switcher" class="btn-outline-secondary nav_options form-control" onchange="switchLanguage()">
                                    <option value="en" {% if request.LANGUAGE_CODE == 'en' %}selected{% endif %}>{% trans "English" %}</option>
                                    <option value="fr" {% if request.LANGUAGE_CODE == 'fr' %}selected{% endif %}>{% trans "French" %}</option>
                                </select>
                            </li>
                            <li class="nav-item">
                                <select id="font-size-switcher" class="btn-outline-secondary nav_options form-control" onchange="changeFontSize()">
                                    <option value="small">{% trans "Small" %}</option>
                                    <option value="medium" selected>{% trans "Medium" %}</option>
                                    <option value="large">{% trans "Large" %}</option>
                                    <option value="vlarge">{% trans "Very Large" %}</option>
                                </select>
                            </li>
                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'automation:password_change' %}">{% trans "Change password" %}</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <form method="post" action="{% url 'automation:logout' %}" id="logout-form">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-link">{% trans "Logout" %}</button>
                                </form>
                                {% else %}
                                <a class="nav_options btn btn-outline-secondary" href="{% url 'automation:login' %}">{% trans "Login" %}</a>
                                {% endif %}
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class=" body_container">
        {% block body %}
        {% endblock %}
    </div>

    <footer class="footer mt-2">
        <div class="container">
            <p>&copy; {% trans "2024 Your Company. All rights reserved." %}</p>
            <p><a href="#">{% trans "Privacy Policy" %}</a> | <a href="#">{% trans "Terms of Service" %}</a></p>
        </div>
    </footer>

    <script src="{% static 'automation/index.js' %}"></script>
    <script>// Language Switcher (Placeholder for actual language switching logic)
        function switchLanguage() {
            const language = document.getElementById('language-switcher').value;
            window.location.href = "{% url 'automation:switch_language' %}?language=" + language;
        }
    </script>
  {% block scripts %}
  {% endblock %}
</body>
</html>